### ISSUE TITLE
Adoptando una arquitectura.

### ISSUE THREAD

**Issue by victormanuelfrancodev** [iosdevelopersmx/charlas#2]
¿Necesitas una arquitectura?
Eres desordenado, te sientes apenado al pasar un año y ver tus post de twitter y fb?, ves tu código después de un año y dices "en qué estaba pensando" o peor aun, no sabes qué hace tu código y no puedes arreglarlo

Necesitas urgentemente una arquitectura

Mi charla hablara de como adopte una arquitectura 
El trayecto que tome para la implementación y los retos que se me presentaron al querer implementarla.
De donde fuiste tomando información
Los resultados.

**Comment by iosdevelopersmx** [comment]
https://www.youtube.com/watch?v=6beOhBrpRU8&t=27s
